### ISSUE TITLE
Updates for Templates 

### ISSUE THREAD

**Issue by anujsrivastava1234** [rishi23root/resume-curator#30]
Two Column -
- [x] Make the Heading of the Projects make it `h6`,  Awards `P` Tag.
- [x] Make the Heading Captilize not  Uppercase.
- [x] Adjust the spacing between the two columns.
- [ ]  Issue in overflow towards the second page.

**Comment by rishi23root** [comment]
@anujsrivastava1234 can you please share your generated resume from the templates you are having issues with

**Comment by rishi23root** [comment]
you can look for a good ATS scoring here - https://resumeworded.com/
all of your suggestion are taken under consideration and updated accordingly 👍️
